# Generated by Django 5.0.6 on 2024-07-20 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
